### ISSUE TITLE
Generate Gantt Chart from Github Issues

### ISSUE THREAD

**Issue by docmarionum1** [wifimapping/app#14]
https://github.com/neyric/gh-issues-gantt

**Comment by DQOfficial** [comment]
So far, unsuccessful. I don't want to commit what I've done so far because it needs me to include my GitHub password, which I'm not going to post online. I'm also 90% sure we can't combine multiple repos onto one Gantt chart.

At this point, I'm going to set up Gantt charts using Google sheets, and then we can continue working on this as needed.
